# Generated by Django 6.0.3 on 2026-03-25 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Остаток товара',
                'verbose_name_plural': 'Остатки товаров',
            },
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
